name: vtpy
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest